### PR TITLE
Add travis multi-os tests and remove cli to fix tests

### PR DESCRIPTION
**Pull request by gmaclennan**
This PR adds travis tests on linux, macos and windows. It removes the CLI (temporarily) in order to fix builds on node 10 and Android – the cli is no longer working with multifeed and it uses an old version of level which does not build on node 10 or Android.

The updated deps (multifeed) is needed to fix tests on WIndows.

### CODE REVIEW

**Comment by noffle** [comment]
weird, still seeing windows failures even on your latest pr

**Comment by noffle** [comment]
weird, still seeing windows failures even on your latest pr

**Comment by gmaclennan** [comment]
Yes, it's an upstream bug in multifeed, I wrote a breaking test here: https://github.com/gmaclennan/multifeed/tree/double-close-bug

**Comment by noffle** [comment]
Fixed in https://github.com/kappa-db/multifeed/pull/24 thanks to @karissa!

**Pull request merged**
